//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulaGamaDBProduto
{
    using System;
    using System.Collections.Generic;
    
    public partial class alimento
    {
        public int IdAlimento { get; set; }
        public Nullable<int> IdProduto { get; set; }
        public string perecivel { get; set; }
        public string validade { get; set; }
    
        public virtual produto produto { get; set; }
    }
}
